### ISSUE TITLE
Problems setting android.permission.WRITE_SECURE_SETTINGS on MIUI devices.

### ISSUE THREAD

**Issue by StephanStanisic** [michaelschattgen/ColorBreeze#2]
I'm just going to link a issue that helped me to set the android.permission.WRITE_SECURE_SETTINGS on a MIUI device.

https://github.com/Genymobile/gnirehtet/issues/5#issuecomment-297045539 
> The issue seems to be resolved by heading over to Developer Options on MIUI, and enabling the following:
> USB debugging -Debug mode when USB is connected
> Install via USB -Allow installing apps via USB
> USB debugging (Security Settings)- Allow granting permissions and simulating input via USB debugging
>
> The first was already enabled, and I installed the apk file manually so I didn't need the second option.

After enableing the _USB debugging (Security Settings)_ option, a few timed dialoges have to be accepted.  
**Don't forget to disable the option after you've set the permission!**

Hopefully this will help someone.

**Comment by PundirPriyanka** [comment]
Getting below error on Redmi note 7 Pro -
Please help .........

[W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C\:\\Users\\priyanka.pundir\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s fcbca55 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 1'; Stderr: ''; Code: '1'
[W3C] Error: Command 'C\:\\Users\\priyanka.pundir\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s fcbca55 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 1
[W3C]     at ChildProcess.proc.on.code (C:\Users\priyanka.pundir\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:94:19)
[W3C]     at ChildProcess.emit (events.js:182:13)
[W3C]     at maybeClose (internal/child_process.js:961:16)
[W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[HTTP] <-- POST /wd/hub/session 500 4017 ms - 1316
[HTTP]
